# Generated by Django 4.0.2 on 2022-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_fame_followers_alter_fame_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='blog.Hashtag', verbose_name='the_Hashtags'),
        ),
    ]
