# Generated by Django 4.0.2 on 2022-03-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(default='blank.png', upload_to='post_images'),
        ),
    ]
