# Generated by Django 4.0.2 on 2022-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='post_images'),
        ),
    ]
