# Generated by Django 4.0.2 on 2022-03-12 13:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
