# Generated by Django 4.0.2 on 2022-03-12 14:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_color',
        ),
        migrations.AddField(
            model_name='post',
            name='content_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='post',
            name='title_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
