# Generated by Django 4.0.2 on 2022-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_text_color_post_content_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(default='default.png', upload_to='post_images'),
        ),
    ]
